name: Sweep Fix

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run code
        run: node examples/all_docs.js

      - name: Handle errors
        run: |
          if [ $? -ne 0 ]; then
            echo "Error: The code execution failed."
            exit 1
          fi
